"""Cria a estrutura inicial das tabelas

Revision ID: 15800f3d9b52
Revises: 
Create Date: 2025-08-30 03:04:16.845017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15800f3d9b52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('carteiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carteiras_id'), 'carteiras', ['id'], unique=False)
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=16), nullable=False),
    sa.Column('validade', sa.String(length=5), nullable=False),
    sa.Column('limite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_cartoes_id'), 'cartoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartoes_id'), table_name='cartoes')
    op.drop_table('cartoes')
    op.drop_index(op.f('ix_carteiras_id'), table_name='carteiras')
    op.drop_table('carteiras')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
