"""Adiciona a tabela de transacoes

Revision ID: 526f846f73ed
Revises: 15800f3d9b52
Create Date: 2025-08-30 05:42:06.871722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526f846f73ed'
down_revision: Union[str, Sequence[str], None] = '15800f3d9b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('carteira_origem_id', sa.Integer(), nullable=False),
    sa.Column('carteira_destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carteira_destino_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['carteira_origem_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_table('transacoes')
    # ### end Alembic commands ###
