name: FinTracker CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Inicia um serviço de banco de dados PostgreSQL para os testes
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar Linting com Flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Rodar Migrações do Alembic
        env:
          # Usa o banco de dados do 'services' do job
          DATABASE_URL: postgresql+psycopg2://testuser:testpassword@localhost:5432/testdb
        run: alembic upgrade head

      - name: Rodar Testes com Pytest
        env:
          DATABASE_URL: postgresql+psycopg2://testuser:testpassword@localhost:5432/testdb
        run: |
          pip install pytest requests
          # Inicia a API em background
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          # Aguarda a API iniciar
          sleep 5
          # Roda os testes
          pytest